[package]
name = "logic_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version = "1.85"

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true

[dev-dependencies]
